-- This file is automatically generated, do not edit!
-- Item data (c) Grinding Gear Games
local itemBases = ...

itemBases["Hayoxi's Soul Core of Heatproofing"] = {
	type = "SoulCore",
	tags = { default = true, soul_core_tier3 = true, soul_core = true, },
	implicitModTypes = { },
